# Generated by Django 5.1.6 on 2025-02-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='vendedora',
        ),
    ]
