# Generated by Django 5.1.6 on 2025-02-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_itemvenda_produto_alter_itemvenda_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
