# Generated by Django 5.1.6 on 2025-02-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_add_frete_field'),
        ('vendas', '0005_venda_finalizada'),
    ]

    operations = [
    ]
