# Generated by Django 5.1.6 on 2025-02-10 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_imagem'),
        ('vendas', '0007_alter_itemvenda_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto'),
        ),
    ]
