# Generated by Django 5.1.6 on 2025-02-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('vendedoras', '0002_remove_vendedora_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueVendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
                ('vendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='vendedoras.vendedora')),
            ],
            options={
                'unique_together': {('vendedora', 'produto')},
            },
        ),
    ]
