# Generated by Django 5.1.6 on 2025-02-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('vendedoras', '0003_estoquevendedora'),
    ]

    operations = [
        migrations.AddField(
            model_name='acerto',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ItemAcerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_vendida', models.IntegerField(default=0)),
                ('quantidade_devolvida', models.IntegerField(default=0)),
                ('acerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendedoras.acerto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
