# Generated by Django 5.1.6 on 2025-02-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0004_acerto_finalizado_itemacerto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemacerto',
            name='acerto',
        ),
        migrations.RemoveField(
            model_name='itemacerto',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Acerto',
        ),
        migrations.DeleteModel(
            name='ItemAcerto',
        ),
    ]
