# Generated by Django 5.1.6 on 2025-02-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clean_cpfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf__isnull', False)), fields=('cpf',), name='unique_non_null_cpf'),
        ),
    ]
